<?php
\defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;

$returnToken=Factory::getApplication()->getInput()->get('return','','BASE64');
$rows=$this->unitItems?:[(object)['exercise_id'=>null,'exercise_title'=>'','duration_minutes'=>15,'goal'=>'','content'=>'','method'=>'','material'=>'','remarks'=>'']];
?>
<div class="jt-training-unit-editor">
 <h1><?php echo Text::_($this->item->id?'COM_JUGENDTRAINING_TRAINING_UNIT_EDIT':'COM_JUGENDTRAINING_TRAINING_UNIT_NEW'); ?></h1>
 <form action="<?php echo Route::_('index.php?option=com_jugendtraining&view=trainertrainingunit&layout=edit&id='.(int)$this->item->id); ?>" method="post" id="adminForm" class="form-validate">
  <section class="card mb-4"><div class="card-header"><h2 class="h4 mb-0"><?php echo Text::_('COM_JUGENDTRAINING_TRAINING_UNIT_DETAILS'); ?></h2></div><div class="card-body"><?php echo $this->form->renderFieldset('details'); ?></div></section>
  <section class="card"><div class="card-header d-flex justify-content-between align-items-center gap-2"><h2 class="h4 mb-0"><?php echo Text::_('COM_JUGENDTRAINING_DIDACTIC_RASTER'); ?></h2><button type="button" class="btn btn-sm btn-outline-primary" id="jt-add-raster-row"><?php echo Text::_('COM_JUGENDTRAINING_RASTER_ADD_ROW'); ?></button></div>
   <div class="card-body"><div id="jt-raster-editor">
    <?php foreach($rows as$index=>$row):?><article class="jt-raster-edit-row" data-row-index="<?php echo$index;?>">
     <div class="jt-raster-edit-head"><strong><?php echo Text::sprintf('COM_JUGENDTRAINING_RASTER_STEP',$index+1); ?></strong><div class="d-flex gap-1"><button type="button" class="btn btn-sm btn-outline-secondary jt-row-up" aria-label="<?php echo Text::_('JLIB_HTML_MOVE_UP'); ?>">↑</button><button type="button" class="btn btn-sm btn-outline-secondary jt-row-down" aria-label="<?php echo Text::_('JLIB_HTML_MOVE_DOWN'); ?>">↓</button><button type="button" class="btn btn-sm btn-outline-danger jt-row-remove"><?php echo Text::_('JACTION_DELETE'); ?></button></div></div>
     <div class="row g-3">
      <div class="col-lg-8"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_RASTER_STEP_TITLE'); ?></label><select class="form-select jt-exercise-select" name="unit_items[<?php echo$index;?>][exercise_id]"><option value="0"><?php echo Text::_('COM_JUGENDTRAINING_RASTER_FREE_STEP'); ?></option><?php foreach($this->exercises as$exercise):?><option value="<?php echo(int)$exercise->id;?>" <?php echo(int)$row->exercise_id===(int)$exercise->id?'selected':'';?>><?php echo htmlspecialchars((string)$exercise->title,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select><input class="form-control mt-2" required maxlength="190" name="unit_items[<?php echo$index;?>][exercise_title]" value="<?php echo htmlspecialchars((string)$row->exercise_title,ENT_QUOTES,'UTF-8');?>" placeholder="<?php echo Text::_('COM_JUGENDTRAINING_RASTER_STEP_TITLE');?>"></div>
      <div class="col-lg-4"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_RASTER_TIME'); ?></label><div class="input-group"><input class="form-control" type="number" min="0" max="1440" name="unit_items[<?php echo$index;?>][duration_minutes]" value="<?php echo(int)$row->duration_minutes;?>"><span class="input-group-text"><?php echo Text::_('COM_JUGENDTRAINING_MINUTES_SHORT');?></span></div></div>
      <?php foreach([['goal','COM_JUGENDTRAINING_RASTER_GOAL',500],['method','COM_JUGENDTRAINING_RASTER_METHOD',255],['material','COM_JUGENDTRAINING_RASTER_MATERIALS',0],['remarks','COM_JUGENDTRAINING_RASTER_REMARKS',1000],['content','COM_JUGENDTRAINING_RASTER_CONTENT',0]] as[$field,$label,$max]):?><div class="col-md-6"><label class="form-label"><?php echo Text::_($label);?></label><textarea class="form-control" rows="2" name="unit_items[<?php echo$index;?>][<?php echo$field;?>]" <?php echo$max?'maxlength="'.$max.'"':'';?>><?php echo htmlspecialchars((string)$row->$field,ENT_QUOTES,'UTF-8');?></textarea></div><?php endforeach; ?>
     </div>
    </article><?php endforeach; ?>
   </div></div>
  </section>
  <div class="jt-sticky-actions d-flex gap-2 mt-4"><button type="button" class="btn btn-primary" onclick="Joomla.submitbutton('trainertrainingunit.save')"><?php echo Text::_('JSAVE');?></button><button type="button" class="btn btn-secondary" onclick="Joomla.submitbutton('trainertrainingunit.cancel')"><?php echo Text::_('JCANCEL');?></button><?php if($this->item->id):?><a class="btn btn-danger ms-auto" href="<?php echo Route::_('index.php?option=com_jugendtraining&task=trainertrainingunit.delete&id='.(int)$this->item->id.'&return='.rawurlencode($returnToken).'&'.Factory::getApplication()->getSession()->getFormToken().'=1');?>" onclick="return confirm('<?php echo Text::_('COM_JUGENDTRAINING_TRAINING_UNIT_DELETE_CONFIRM');?>');"><?php echo Text::_('JACTION_DELETE');?></a><?php endif;?></div>
  <input type="hidden" name="task" value=""><input type="hidden" name="return" value="<?php echo htmlspecialchars($returnToken,ENT_QUOTES,'UTF-8');?>"><?php echo HTMLHelper::_('form.token'); ?>
 </form>
</div>
<template id="jt-raster-row-template"><article class="jt-raster-edit-row"><div class="jt-raster-edit-head"><strong></strong><div class="d-flex gap-1"><button type="button" class="btn btn-sm btn-outline-secondary jt-row-up">↑</button><button type="button" class="btn btn-sm btn-outline-secondary jt-row-down">↓</button><button type="button" class="btn btn-sm btn-outline-danger jt-row-remove"><?php echo Text::_('JACTION_DELETE');?></button></div></div><div class="row g-3"><div class="col-lg-8"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_RASTER_STEP_TITLE');?></label><select class="form-select jt-exercise-select" data-field="exercise_id"><option value="0"><?php echo Text::_('COM_JUGENDTRAINING_RASTER_FREE_STEP');?></option><?php foreach($this->exercises as$exercise):?><option value="<?php echo(int)$exercise->id;?>"><?php echo htmlspecialchars((string)$exercise->title,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select><input class="form-control mt-2" required maxlength="190" data-field="exercise_title" placeholder="<?php echo Text::_('COM_JUGENDTRAINING_RASTER_STEP_TITLE');?>"></div><div class="col-lg-4"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_RASTER_TIME');?></label><div class="input-group"><input class="form-control" type="number" min="0" max="1440" value="15" data-field="duration_minutes"><span class="input-group-text"><?php echo Text::_('COM_JUGENDTRAINING_MINUTES_SHORT');?></span></div></div><?php foreach([['goal','COM_JUGENDTRAINING_RASTER_GOAL'],['method','COM_JUGENDTRAINING_RASTER_METHOD'],['material','COM_JUGENDTRAINING_RASTER_MATERIALS'],['remarks','COM_JUGENDTRAINING_RASTER_REMARKS'],['content','COM_JUGENDTRAINING_RASTER_CONTENT']] as[$field,$label]):?><div class="col-md-6"><label class="form-label"><?php echo Text::_($label);?></label><textarea class="form-control" rows="2" data-field="<?php echo$field;?>"></textarea></div><?php endforeach;?></div></article></template>
<script>document.addEventListener('DOMContentLoaded',()=>{const root=document.getElementById('jt-raster-editor'),template=document.getElementById('jt-raster-row-template');if(!root||!template)return;const renumber=()=>{[...root.children].forEach((row,i)=>{row.dataset.rowIndex=i;row.querySelector('strong').textContent=<?php echo json_encode(Text::_('COM_JUGENDTRAINING_RASTER_STEP'));?>.replace('%s',i+1);row.querySelectorAll('[name],[data-field]').forEach(field=>{const key=field.dataset.field||field.name.match(/\[([^\]]+)\]$/)?.[1];if(key)field.name=`unit_items[${i}][${key}]`;});});};root.addEventListener('click',event=>{const row=event.target.closest('.jt-raster-edit-row');if(!row)return;if(event.target.closest('.jt-row-remove'))row.remove();else if(event.target.closest('.jt-row-up')&&row.previousElementSibling)root.insertBefore(row,row.previousElementSibling);else if(event.target.closest('.jt-row-down')&&row.nextElementSibling)root.insertBefore(row.nextElementSibling,row);renumber();});root.addEventListener('change',event=>{const select=event.target.closest('.jt-exercise-select');if(!select||select.value==='0')return;const title=select.closest('.jt-raster-edit-row')?.querySelector('[name$="[exercise_title]"]');if(title&&!title.value.trim())title.value=select.options[select.selectedIndex].text;});document.getElementById('jt-add-raster-row').addEventListener('click',()=>{root.append(template.content.cloneNode(true));renumber();});renumber();});</script>
