<?php
\defined('_JEXEC') or die;
use Joomla\CMS\Factory;use Joomla\CMS\HTML\HTMLHelper;use Joomla\CMS\Language\Text;use Joomla\CMS\Router\Route;
$app=Factory::getApplication();$mode=$app->input->getCmd('mode','future');$category=$app->input->getString('category');$location=$app->input->getString('location');$from=$app->input->getString('date_from');$to=$app->input->getString('date_to');$e=$this->editEvent;
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="mb-1"><?php echo Text::_('COM_JUGENDTRAINING_CALENDAR');?></h1><p class="text-muted mb-0"><?php echo Text::_('COM_JUGENDTRAINING_CALENDAR_TRAINER_INTRO');?></p></div><a class="btn btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=trainerdashboard');?>"><?php echo Text::_('COM_JUGENDTRAINING_BACK_TO_DASHBOARD');?></a></div>

<div class="card mb-4" id="calendar-editor"><div class="card-header"><h2 class="h4 mb-0"><?php echo Text::_($e?'COM_JUGENDTRAINING_EDIT_EVENT':'COM_JUGENDTRAINING_ADD_EVENT');?></h2></div><div class="card-body">
<form action="<?php echo Route::_('index.php?option=com_jugendtraining&task=trainercalendar.save');?>" method="post" enctype="multipart/form-data">
<input type="hidden" name="jform[id]" value="<?php echo(int)($e->id??0);?>">
<div class="row g-3">
<div class="col-md-6"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_EVENT_TITLE');?></label><input class="form-control" name="jform[title]" maxlength="190" required value="<?php echo htmlspecialchars((string)($e->title??''),ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-3"><label class="form-label"><?php echo Text::_('JDATE');?></label><input class="form-control" type="date" name="jform[event_date]" required value="<?php echo htmlspecialchars((string)($e->event_date??''),ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-3"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_TIME');?></label><input class="form-control" type="time" name="jform[event_time]" value="<?php echo htmlspecialchars(substr((string)($e->event_time??''),0,5),ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-4"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_CATEGORY');?></label><select class="form-select" name="jform[category]" required><option value=""><?php echo Text::_('COM_JUGENDTRAINING_SELECT_OPTION');?></option><?php foreach($this->categories as$c):?><option value="<?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?>" <?php echo($e->category??'')===$c?'selected':'';?>><?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div>
<div class="col-md-6"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_LOCATION');?></label><input class="form-control" name="jform[location]" maxlength="190" list="calendar-locations" value="<?php echo htmlspecialchars((string)($e->location??''),ENT_QUOTES,'UTF-8');?>"><datalist id="calendar-locations"><?php foreach($this->locations as$l):?><option value="<?php echo htmlspecialchars($l,ENT_QUOTES,'UTF-8');?>"><?php endforeach;?></datalist></div>
<div class="col-md-2 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="jform[published]" value="1" <?php echo!isset($e->published)||(int)$e->published===1?'checked':'';?>><label class="form-check-label"><?php echo Text::_('JPUBLISHED');?></label></div></div>
<div class="col-12"><label class="form-label"><?php echo Text::_('JGLOBAL_DESCRIPTION');?></label><textarea class="form-control" name="jform[description]" rows="3" maxlength="10000"><?php echo htmlspecialchars((string)($e->description??''),ENT_QUOTES,'UTF-8');?></textarea></div>
<div class="col-12"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_PDF_ATTACHMENTS');?></label><input class="form-control" type="file" name="attachments[]" accept="application/pdf,.pdf" multiple><div class="form-text"><?php echo Text::_('COM_JUGENDTRAINING_PDF_ATTACHMENTS_HELP');?></div></div>
<?php if($e&&!empty($e->attachments)):?><div class="col-12"><strong><?php echo Text::_('COM_JUGENDTRAINING_EXISTING_ATTACHMENTS');?></strong><div class="d-flex flex-wrap gap-2 mt-2"><?php foreach($e->attachments as$a):?><a class="btn btn-sm btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_jugendtraining&task=calendarattachment.download&id='.(int)$a->id);?>">📎 <?php echo htmlspecialchars($a->file_name,ENT_QUOTES,'UTF-8');?></a><?php endforeach;?></div></div><?php endif;?>
</div>
<div class="mt-3 d-flex gap-2"><button class="btn btn-primary" type="submit"><?php echo Text::_('JSAVE');?></button><?php if($e):?><a class="btn btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=trainercalendar');?>"><?php echo Text::_('JCANCEL');?></a><?php endif;?></div><?php echo HTMLHelper::_('form.token');?>
</form></div></div>

<form class="card card-body mb-4" method="get"><input type="hidden" name="option" value="com_jugendtraining"><input type="hidden" name="view" value="trainercalendar">
<div class="row g-3 align-items-end">
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_PERIOD');?></label><select class="form-select" name="mode"><option value="future" <?php echo$mode==='future'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_FUTURE');?></option><option value="past" <?php echo$mode==='past'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_PAST');?></option><option value="all" <?php echo$mode==='all'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option></select></div>
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_DATE_FROM');?></label><input class="form-control" type="date" name="date_from" value="<?php echo htmlspecialchars($from,ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_DATE_TO');?></label><input class="form-control" type="date" name="date_to" value="<?php echo htmlspecialchars($to,ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_CATEGORY');?></label><select class="form-select" name="category"><option value=""><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option><?php foreach($this->categories as$c):?><option value="<?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?>" <?php echo$category===$c?'selected':'';?>><?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div>
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_LOCATION');?></label><select class="form-select" name="location"><option value=""><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option><?php foreach($this->locations as$l):?><option value="<?php echo htmlspecialchars($l,ENT_QUOTES,'UTF-8');?>" <?php echo$location===$l?'selected':'';?>><?php echo htmlspecialchars($l,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div>
<div class="col-md-2"><button class="btn btn-primary w-100" type="submit"><?php echo Text::_('COM_JUGENDTRAINING_FILTER');?></button></div>
</div></form>

<?php if($this->events):?><div class="row g-3"><?php foreach($this->events as$event):?><div class="col-12"><article class="card"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-3">
<div><div class="d-flex flex-wrap gap-2 align-items-center mb-1"><span class="badge text-bg-primary"><?php echo htmlspecialchars($event->category,ENT_QUOTES,'UTF-8');?></span><?php if(!(int)$event->published):?><span class="badge text-bg-secondary"><?php echo Text::_('JUNPUBLISHED');?></span><?php endif;?></div><h2 class="h4 mb-1"><?php echo htmlspecialchars($event->title,ENT_QUOTES,'UTF-8');?></h2><div class="text-muted"><?php echo HTMLHelper::_('date',$event->event_date,Text::_('DATE_FORMAT_LC4'));?><?php if($event->event_time):?> · <?php echo htmlspecialchars(substr($event->event_time,0,5),ENT_QUOTES,'UTF-8');?> Uhr<?php endif;?><?php if($event->location):?> · <?php echo htmlspecialchars($event->location,ENT_QUOTES,'UTF-8');?><?php endif;?></div><?php if($event->description):?><p class="mt-2 mb-0"><?php echo nl2br(htmlspecialchars($event->description,ENT_QUOTES,'UTF-8'));?></p><?php endif;?></div>
<div class="text-end"><div class="d-flex gap-2"><a class="btn btn-sm btn-outline-primary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=trainercalendar&edit_id='.(int)$event->id.'#calendar-editor');?>"><?php echo Text::_('JACTION_EDIT');?></a><form action="<?php echo Route::_('index.php?option=com_jugendtraining&task=trainercalendar.delete');?>" method="post" onsubmit="return confirm('<?php echo Text::_('COM_JUGENDTRAINING_DELETE_EVENT_CONFIRM');?>');"><input type="hidden" name="id" value="<?php echo(int)$event->id;?>"><button class="btn btn-sm btn-outline-danger" type="submit"><?php echo Text::_('JACTION_DELETE');?></button><?php echo HTMLHelper::_('form.token');?></form></div><?php if((int)$event->attachment_count>0):?><div class="small text-muted mt-2"><?php echo(int)$event->attachment_count;?> PDF</div><?php endif;?></div>
</div></div></article></div><?php endforeach;?></div><?php else:?><div class="alert alert-info"><?php echo Text::_('COM_JUGENDTRAINING_NO_CALENDAR_EVENTS');?></div><?php endif;?>
