<?php
\defined('_JEXEC') or die;
use Joomla\CMS\Factory;use Joomla\CMS\HTML\HTMLHelper;use Joomla\CMS\Language\Text;use Joomla\CMS\Router\Route;
$app=Factory::getApplication();$mode=$app->input->getCmd('mode','future');$from=$app->input->getString('date_from');$to=$app->input->getString('date_to');$category=$app->input->getString('category');$location=$app->input->getString('location');$e=$this->editEvent;
?>
<div class="card mb-4" id="calendar-editor"><div class="card-header"><h2 class="h4 mb-0"><?php echo Text::_($e?'COM_JUGENDTRAINING_EDIT_EVENT':'COM_JUGENDTRAINING_ADD_EVENT');?></h2></div><div class="card-body"><form action="<?php echo Route::_('index.php?option=com_jugendtraining&task=calendar.save');?>" method="post" enctype="multipart/form-data"><input type="hidden" name="jform[id]" value="<?php echo(int)($e->id??0);?>"><div class="row g-3">
<div class="col-md-5"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_EVENT_TITLE');?></label><input class="form-control" name="jform[title]" required maxlength="190" value="<?php echo htmlspecialchars((string)($e->title??''),ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-2"><label class="form-label"><?php echo Text::_('JDATE');?></label><input class="form-control" type="date" name="jform[event_date]" required value="<?php echo htmlspecialchars((string)($e->event_date??''),ENT_QUOTES,'UTF-8');?>"></div><div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_TIME');?></label><input class="form-control" type="time" name="jform[event_time]" value="<?php echo htmlspecialchars(substr((string)($e->event_time??''),0,5),ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-3"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_CATEGORY');?></label><select class="form-select" name="jform[category]" required><?php foreach($this->categories as$c):?><option value="<?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?>" <?php echo($e->category??'')===$c?'selected':'';?>><?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div>
<div class="col-md-8"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_LOCATION');?></label><input class="form-control" name="jform[location]" maxlength="190" value="<?php echo htmlspecialchars((string)($e->location??''),ENT_QUOTES,'UTF-8');?>"></div><div class="col-md-4 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="jform[published]" value="1" <?php echo!isset($e->published)||(int)$e->published===1?'checked':'';?>><label class="form-check-label"><?php echo Text::_('JPUBLISHED');?></label></div></div>
<div class="col-12"><label class="form-label"><?php echo Text::_('JGLOBAL_DESCRIPTION');?></label><textarea class="form-control" name="jform[description]" rows="3"><?php echo htmlspecialchars((string)($e->description??''),ENT_QUOTES,'UTF-8');?></textarea></div>
<div class="col-12"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_PDF_ATTACHMENTS');?></label><input class="form-control" type="file" name="attachments[]" accept="application/pdf,.pdf" multiple><div class="form-text"><?php echo Text::_('COM_JUGENDTRAINING_PDF_ATTACHMENTS_HELP');?></div></div>
</div><div class="mt-3 d-flex gap-2"><button class="btn btn-success" type="submit"><?php echo Text::_('JSAVE');?></button><?php if($e):?><a class="btn btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=calendar');?>"><?php echo Text::_('JCANCEL');?></a><?php endif;?></div><?php echo HTMLHelper::_('form.token');?></form></div></div>
<form class="card card-body mb-4" method="get"><input type="hidden" name="option" value="com_jugendtraining"><input type="hidden" name="view" value="calendar"><div class="row g-3 align-items-end"><div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_PERIOD');?></label><select class="form-select" name="mode"><option value="future" <?php echo$mode==='future'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_FUTURE');?></option><option value="past" <?php echo$mode==='past'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_PAST');?></option><option value="all" <?php echo$mode==='all'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option></select></div><div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_DATE_FROM');?></label><input class="form-control" type="date" name="date_from" value="<?php echo htmlspecialchars($from,ENT_QUOTES,'UTF-8');?>"></div><div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_DATE_TO');?></label><input class="form-control" type="date" name="date_to" value="<?php echo htmlspecialchars($to,ENT_QUOTES,'UTF-8');?>"></div><div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_CATEGORY');?></label><select class="form-select" name="category"><option value=""><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option><?php foreach($this->categories as$c):?><option value="<?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?>" <?php echo$category===$c?'selected':'';?>><?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_LOCATION');?></label><select class="form-select" name="location"><option value=""><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option><?php foreach($this->locations as$l):?><option value="<?php echo htmlspecialchars($l,ENT_QUOTES,'UTF-8');?>" <?php echo$location===$l?'selected':'';?>><?php echo htmlspecialchars($l,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><?php echo Text::_('COM_JUGENDTRAINING_FILTER');?></button></div></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th><?php echo Text::_('JDATE');?></th><th><?php echo Text::_('COM_JUGENDTRAINING_EVENT_TITLE');?></th><th><?php echo Text::_('COM_JUGENDTRAINING_CATEGORY');?></th><th><?php echo Text::_('COM_JUGENDTRAINING_LOCATION');?></th><th>PDF</th><th></th></tr></thead><tbody><?php foreach($this->events as$x):?><tr><td><?php echo HTMLHelper::_('date',$x->event_date,Text::_('DATE_FORMAT_LC4'));?><?php if($x->event_time):?><div class="small text-muted"><?php echo htmlspecialchars(substr($x->event_time,0,5),ENT_QUOTES,'UTF-8');?></div><?php endif;?></td><td><strong><?php echo htmlspecialchars($x->title,ENT_QUOTES,'UTF-8');?></strong></td><td><?php echo htmlspecialchars($x->category,ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars((string)$x->location,ENT_QUOTES,'UTF-8');?></td><td><?php echo(int)$x->attachment_count;?></td><td class="text-end"><div class="d-flex justify-content-end gap-2"><a class="btn btn-sm btn-outline-primary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=calendar&edit_id='.(int)$x->id.'#calendar-editor');?>"><?php echo Text::_('JACTION_EDIT');?></a><form method="post" action="<?php echo Route::_('index.php?option=com_jugendtraining&task=calendar.delete');?>" onsubmit="return confirm('<?php echo Text::_('COM_JUGENDTRAINING_DELETE_EVENT_CONFIRM');?>');"><input type="hidden" name="id" value="<?php echo(int)$x->id;?>"><button class="btn btn-sm btn-outline-danger"><?php echo Text::_('JACTION_DELETE');?></button><?php echo HTMLHelper::_('form.token');?></form></div></td></tr><?php endforeach;?></tbody></table></div>
