<?php
\defined('_JEXEC') or die;
use Joomla\CMS\Factory;use Joomla\CMS\Language\Text;use Joomla\CMS\HTML\HTMLHelper;use Joomla\CMS\Router\Route;use Joomla\CMS\Session\Session;
$app=Factory::getApplication();$status=$app->input->getCmd('status','current');$groupId=$app->input->getInt('group_id');$athleteId=$app->input->getInt('athlete_id');
$edit=$this->editNote;$selectedAthlete=$edit?(int)$edit->athlete_id:$athleteId;
?>
<div class="d-flex justify-content-between align-items-center gap-3 mb-4">
 <h1 class="mb-0"><?php echo Text::_('COM_JUGENDTRAINING_TRAINER_NOTES');?></h1>
 <a class="btn btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=trainerdashboard');?>"><?php echo Text::_('COM_JUGENDTRAINING_BACK_TO_DASHBOARD');?></a>
</div>

<div class="card mb-4" id="note-editor"><div class="card-header"><h2 class="h4 mb-0"><?php echo Text::_($edit?'COM_JUGENDTRAINING_EDIT_NOTE':'COM_JUGENDTRAINING_ADD_NOTE');?></h2></div><div class="card-body">
<form action="<?php echo Route::_('index.php?option=com_jugendtraining&task=trainernotesfront.save');?>" method="post" class="row g-3">
<input type="hidden" name="jform[id]" value="<?php echo(int)($edit->id??0);?>">
<div class="col-md-4"><label class="form-label" for="note-athlete"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_ATHLETE');?></label><select class="form-select" id="note-athlete" name="jform[athlete_id]" required><option value=""><?php echo Text::_('COM_JUGENDTRAINING_SELECT_OPTION');?></option><?php foreach($this->athletes as$a):?><option value="<?php echo(int)$a->id;?>" <?php echo$selectedAthlete===(int)$a->id?'selected':'';?>><?php echo htmlspecialchars($a->firstname.' '.$a->lastname,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label" for="note-date"><?php echo Text::_('JDATE');?></label><input class="form-control" type="date" id="note-date" name="jform[note_date]" value="<?php echo htmlspecialchars((string)($edit->note_date??date('Y-m-d')),ENT_QUOTES,'UTF-8');?>" required></div>
<div class="col-md-3"><label class="form-label" for="note-category"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_CATEGORY');?></label><input class="form-control" id="note-category" name="jform[category]" value="<?php echo htmlspecialchars((string)($edit->category??'general'),ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-2"><label class="form-label" for="note-status"><?php echo Text::_('JSTATUS');?></label><select class="form-select" id="note-status" name="jform[status]"><option value="current" <?php echo($edit->status??'current')==='current'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_NOTE_CURRENT');?></option><option value="done" <?php echo($edit->status??'current')==='done'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_NOTE_DONE');?></option></select></div>
<div class="col-12"><label class="form-label" for="note-text"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_NOTE');?></label><textarea class="form-control" id="note-text" name="jform[note]" rows="4" required><?php echo htmlspecialchars((string)($edit->note??''),ENT_QUOTES,'UTF-8');?></textarea></div>
<div class="col-12 d-flex flex-wrap gap-3 align-items-center"><div class="form-check"><input class="form-check-input" type="checkbox" id="private-note" name="jform[private_note]" value="1" <?php echo!isset($edit->private_note)||(int)$edit->private_note===1?'checked':'';?>><label class="form-check-label" for="private-note"><?php echo Text::_('COM_JUGENDTRAINING_PRIVATE_NOTE');?></label></div><button class="btn btn-primary" type="submit"><?php echo Text::_('COM_JUGENDTRAINING_SAVE');?></button><?php if($edit):?><a class="btn btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=trainernotesfront&athlete_id='.(int)$edit->athlete_id);?>"><?php echo Text::_('JCANCEL');?></a><?php endif;?></div>
<?php echo HTMLHelper::_('form.token');?>
</form></div></div>

<form class="card card-body mb-4" method="get"><input type="hidden" name="option" value="com_jugendtraining"><input type="hidden" name="view" value="trainernotesfront"><div class="row g-3 align-items-end">
<div class="col-md-4"><label class="form-label" for="filter-group"><?php echo Text::_('COM_JUGENDTRAINING_TRAINING_GROUP');?></label><select class="form-select" id="filter-group" name="group_id"><option value="0"><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option><?php foreach($this->groups as$g):?><option value="<?php echo(int)$g->id;?>" <?php echo$groupId===(int)$g->id?'selected':'';?>><?php echo htmlspecialchars($g->title,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label class="form-label" for="filter-athlete"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_ATHLETE');?></label><select class="form-select" id="filter-athlete" name="athlete_id"><option value="0"><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option><?php foreach($this->athletes as$a):?><option value="<?php echo(int)$a->id;?>" <?php echo$athleteId===(int)$a->id?'selected':'';?>><?php echo htmlspecialchars($a->firstname.' '.$a->lastname,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div>
<div class="col-md-2"><label class="form-label" for="filter-status"><?php echo Text::_('JSTATUS');?></label><select class="form-select" id="filter-status" name="status"><option value="current" <?php echo$status==='current'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_NOTE_CURRENT');?></option><option value="done" <?php echo$status==='done'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_NOTE_DONE');?></option><option value="all" <?php echo$status==='all'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option></select></div>
<div class="col-md-2"><button class="btn btn-primary w-100" type="submit"><?php echo Text::_('COM_JUGENDTRAINING_FILTER');?></button></div></div></form>

<?php if($this->notes):foreach($this->notes as$n):?>
<div class="card mb-3"><div class="card-body"><div class="d-flex justify-content-between gap-3">
<div><div class="small text-muted"><?php echo HTMLHelper::_('date',$n->note_date,Text::_('DATE_FORMAT_LC4'));?> · <?php echo htmlspecialchars($n->athlete_name,ENT_QUOTES,'UTF-8');?> · <?php echo htmlspecialchars((string)$n->group_names,ENT_QUOTES,'UTF-8');?></div><p class="mb-0 mt-2"><?php echo nl2br(htmlspecialchars($n->note,ENT_QUOTES,'UTF-8'));?></p></div>
<div class="text-end"><span class="badge <?php echo$n->status==='done'?'text-bg-success':'text-bg-warning';?>"><?php echo Text::_($n->status==='done'?'COM_JUGENDTRAINING_NOTE_DONE':'COM_JUGENDTRAINING_NOTE_CURRENT');?></span><div class="mt-2 d-flex gap-2"><a class="btn btn-sm btn-outline-primary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=trainernotesfront&edit_id='.(int)$n->id.'&athlete_id='.(int)$n->athlete_id.'#note-editor');?>"><?php echo Text::_('JACTION_EDIT');?></a><a class="btn btn-sm btn-outline-primary" href="<?php echo Route::_('index.php?option=com_jugendtraining&task=trainernotesfront.status&id='.(int)$n->id.'&status='.($n->status==='done'?'current':'done').'&'.Session::getFormToken().'=1');?>"><?php echo Text::_($n->status==='done'?'COM_JUGENDTRAINING_MARK_CURRENT':'COM_JUGENDTRAINING_MARK_DONE');?></a></div></div>
</div></div></div>
<?php endforeach;else:?><div class="alert alert-info"><?php echo Text::_('COM_JUGENDTRAINING_NO_NOTES');?></div><?php endif;?>
