<?php
namespace Jugendtraining\Component\Jugendtraining\Site\Service;
\defined('_JEXEC') or die;
use Joomla\CMS\Factory;use Joomla\Database\DatabaseInterface;
final class SelfCheckinService
{
 private DatabaseInterface $db;private AccessService $access;
 public function __construct(){$this->db=Factory::getContainer()->get(DatabaseInterface::class);$this->access=new AccessService();}
 public function settings():object{$keys=['self_checkin_enabled','self_checkin_radius_m','self_checkin_lead_minutes','self_checkin_fallback_duration_minutes'];$q=$this->db->getQuery(true)->select(['setting_key','setting_value'])->from('#__jt_settings')->where('setting_key IN ('.implode(',',array_map([$this->db,'quote'],$keys)).')');$this->db->setQuery($q);$r=$this->db->loadAssocList('setting_key','setting_value');return(object)['enabled'=>(int)($r['self_checkin_enabled']??0)===1,'radius_m'=>max(10,min(5000,(int)($r['self_checkin_radius_m']??100))),'lead_minutes'=>max(0,min(1440,(int)($r['self_checkin_lead_minutes']??60))),'fallback_duration_minutes'=>max(1,min(1440,(int)($r['self_checkin_fallback_duration_minutes']??120)))];}
 public function athlete():?object{$u=Factory::getApplication()->getIdentity();if($u->guest||!$this->access->isAthlete($u))return null;$q=$this->db->getQuery(true)->select(['id','firstname','lastname'])->from('#__jt_athletes')->where('user_id='.(int)$u->id)->where('published=1');$this->db->setQuery($q,0,1);return$this->db->loadObject()?:null;}
 public function eligibleSessions():array{$cfg=$this->settings();if(!$cfg->enabled)return[];$athlete=$this->athlete();if(!$athlete)return[];$tz=$this->timezone();$now=new \DateTimeImmutable('now',$tz);$dates=[];for($i=-1;$i<=1;$i++)$dates[]=$now->modify(($i>=0?'+':'').$i.' day')->format('Y-m-d');$q=$this->db->getQuery(true)->select(['s.id','s.title','s.training_date','s.start_time','s.end_time','s.location_id','l.name location_name','l.address','a.status attendance_status'])->from('#__jt_training_sessions s')->innerJoin('#__jt_training_group_athletes ga ON ga.group_id=s.training_group_id AND ga.athlete_id='.(int)$athlete->id)->innerJoin('#__jt_training_locations l ON l.id=s.location_id AND l.published=1')->leftJoin('#__jt_attendance a ON a.training_session_id=s.id AND a.athlete_id='.(int)$athlete->id)->where('s.published=1')->where('s.cancelled=0')->where('s.start_time IS NOT NULL')->where('s.training_date IN ('.implode(',',array_map(fn($d)=>$this->db->quote($d),$dates)).')')->order('s.training_date,s.start_time,s.id');$this->db->setQuery($q);$out=[];foreach($this->db->loadObjectList() as$row){[$open,$close]=$this->window($row,$cfg,$tz);if($now<$open||$now>$close)continue;$row->start_local=$this->sessionStart($row,$tz)->format('Y-m-d H:i:s');$row->checkin_open_local=$open->format('Y-m-d H:i:s');$row->checkin_close_local=$close->format('Y-m-d H:i:s');$out[]=$row;}return$out;}
 public function checkin(int$sessionId,float$latitude,float$longitude):float{$cfg=$this->settings();if(!$cfg->enabled)throw new \RuntimeException('COM_JUGENDTRAINING_SELF_CHECKIN_DISABLED');if($latitude < -90||$latitude > 90||$longitude < -180||$longitude > 180)throw new \RuntimeException('COM_JUGENDTRAINING_SELF_CHECKIN_INVALID_POSITION');$athlete=$this->athlete();if(!$athlete)throw new \RuntimeException('JERROR_ALERTNOAUTHOR',403);$session=$this->sessionForAthlete($sessionId,(int)$athlete->id);if(!$session)throw new \RuntimeException('JERROR_ALERTNOAUTHOR',403);if(!$session->start_time)throw new \RuntimeException('COM_JUGENDTRAINING_SELF_CHECKIN_NO_START_TIME');$tz=$this->timezone();$now=new \DateTimeImmutable('now',$tz);[$open,$close]=$this->window($session,$cfg,$tz);if($now<$open||$now>$close)throw new \RuntimeException('COM_JUGENDTRAINING_SELF_CHECKIN_OUTSIDE_WINDOW');$distance=$this->distanceMeters($latitude,$longitude,(float)$session->latitude,(float)$session->longitude);if($distance>$cfg->radius_m)throw new \RuntimeException('COM_JUGENDTRAINING_SELF_CHECKIN_OUTSIDE_GEOFENCE');$uid=(int)Factory::getApplication()->getIdentity()->id;$nowSql=Factory::getDate()->toSql();$q=$this->db->getQuery(true)->select('id')->from('#__jt_attendance')->where('training_session_id='.$sessionId)->where('athlete_id='.(int)$athlete->id);$this->db->setQuery($q);$id=(int)$this->db->loadResult();if($id){$o=(object)['id'=>$id,'status'=>'present','modified'=>$nowSql,'modified_by'=>$uid];$this->db->updateObject('#__jt_attendance',$o,'id');}else{$o=(object)['training_session_id'=>$sessionId,'athlete_id'=>(int)$athlete->id,'status'=>'present','comment'=>null,'created'=>$nowSql,'created_by'=>$uid,'modified'=>$nowSql,'modified_by'=>$uid];$this->db->insertObject('#__jt_attendance',$o);}$this->audit((int)$athlete->id,$sessionId,$distance,$cfg->radius_m);return$distance;}
 private function sessionForAthlete(int$id,int$athleteId):?object{$q=$this->db->getQuery(true)->select(['s.id','s.training_date','s.start_time','s.end_time','s.location_id','l.latitude','l.longitude'])->from('#__jt_training_sessions s')->innerJoin('#__jt_training_group_athletes ga ON ga.group_id=s.training_group_id AND ga.athlete_id='.$athleteId)->innerJoin('#__jt_training_locations l ON l.id=s.location_id AND l.published=1')->where('s.id='.$id)->where('s.published=1')->where('s.cancelled=0');$this->db->setQuery($q,0,1);return$this->db->loadObject()?:null;}
 private function window(object$s,object$cfg,\DateTimeZone$tz):array{$start=$this->sessionStart($s,$tz);$open=$start->modify('-'.(int)$cfg->lead_minutes.' minutes');$end=trim((string)($s->end_time??''));if($end!==''){$close=new \DateTimeImmutable((string)$s->training_date.' '.substr($end,0,8),$tz);if($close<$start)$close=$close->modify('+1 day');}else{$close=$start->modify('+'.(int)$cfg->fallback_duration_minutes.' minutes');}return[$open,$close];}
 private function sessionStart(object$s,\DateTimeZone$tz):\DateTimeImmutable{return new \DateTimeImmutable((string)$s->training_date.' '.substr((string)$s->start_time,0,8),$tz);}
 private function timezone():\DateTimeZone{$name=(string)Factory::getApplication()->get('offset','UTC');try{return new \DateTimeZone($name?:'UTC');}catch(\Throwable){return new \DateTimeZone('UTC');}}
 private function distanceMeters(float$lat1,float$lon1,float$lat2,float$lon2):float{$r=6371000.0;$p1=deg2rad($lat1);$p2=deg2rad($lat2);$dp=deg2rad($lat2-$lat1);$dl=deg2rad($lon2-$lon1);$a=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return$r*2*atan2(sqrt($a),sqrt(1-$a));}
 private function audit(int$athleteId,int$sessionId,float$distance,int$radius):void{$payload=json_encode(['training_session_id'=>$sessionId,'distance_m'=>round($distance,1),'radius_m'=>$radius],JSON_UNESCAPED_UNICODE);$o=(object)['user_id'=>(int)Factory::getApplication()->getIdentity()->id,'action'=>'self_checkin','entity_type'=>'athlete','entity_id'=>$athleteId,'payload'=>$payload,'created'=>Factory::getDate()->toSql()];$this->db->insertObject('#__jt_audit_log',$o);}
}
