<?php
\defined('_JEXEC') or die;
use Joomla\CMS\Factory;use Joomla\CMS\HTML\HTMLHelper;use Joomla\CMS\Language\Text;use Joomla\CMS\Router\Route;
$app=Factory::getApplication();$mode=$app->input->getCmd('mode','future');$category=$app->input->getString('category');$location=$app->input->getString('location');$from=$app->input->getString('date_from');$to=$app->input->getString('date_to');
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="mb-1"><?php echo Text::_('COM_JUGENDTRAINING_CALENDAR');?></h1><p class="text-muted mb-0"><?php echo Text::_('COM_JUGENDTRAINING_CALENDAR_ATHLETE_INTRO');?></p></div><a class="btn btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=dashboard');?>"><?php echo Text::_('COM_JUGENDTRAINING_BACK_TO_DASHBOARD');?></a></div>
<form class="card card-body mb-4" method="get"><input type="hidden" name="option" value="com_jugendtraining"><input type="hidden" name="view" value="athletecalendar"><div class="row g-3 align-items-end">
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_PERIOD');?></label><select class="form-select" name="mode"><option value="future" <?php echo$mode==='future'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_FUTURE');?></option><option value="past" <?php echo$mode==='past'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_PAST');?></option><option value="all" <?php echo$mode==='all'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option></select></div>
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_DATE_FROM');?></label><input class="form-control" type="date" name="date_from" value="<?php echo htmlspecialchars($from,ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_DATE_TO');?></label><input class="form-control" type="date" name="date_to" value="<?php echo htmlspecialchars($to,ENT_QUOTES,'UTF-8');?>"></div>
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_CATEGORY');?></label><select class="form-select" name="category"><option value=""><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option><?php foreach($this->categories as$c):?><option value="<?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?>" <?php echo$category===$c?'selected':'';?>><?php echo htmlspecialchars($c,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div>
<div class="col-md-2"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_LOCATION');?></label><select class="form-select" name="location"><option value=""><?php echo Text::_('COM_JUGENDTRAINING_ALL');?></option><?php foreach($this->locations as$l):?><option value="<?php echo htmlspecialchars($l,ENT_QUOTES,'UTF-8');?>" <?php echo$location===$l?'selected':'';?>><?php echo htmlspecialchars($l,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div>
<div class="col-md-2"><button class="btn btn-primary w-100" type="submit"><?php echo Text::_('COM_JUGENDTRAINING_FILTER');?></button></div>
</div></form>
<?php if($this->events):?><div class="row g-3"><?php foreach($this->events as$event):?><div class="col-12 col-lg-6"><article class="card h-100"><div class="card-body"><span class="badge text-bg-primary"><?php echo htmlspecialchars($event->category,ENT_QUOTES,'UTF-8');?></span><h2 class="h4 mt-2 mb-1"><?php echo htmlspecialchars($event->title,ENT_QUOTES,'UTF-8');?></h2><div class="text-muted mb-2"><?php echo HTMLHelper::_('date',$event->event_date,Text::_('DATE_FORMAT_LC4'));?><?php if($event->event_time):?> · <?php echo htmlspecialchars(substr($event->event_time,0,5),ENT_QUOTES,'UTF-8');?> Uhr<?php endif;?><?php if($event->location):?> · <?php echo htmlspecialchars($event->location,ENT_QUOTES,'UTF-8');?><?php endif;?></div><?php if($event->description):?><p><?php echo nl2br(htmlspecialchars($event->description,ENT_QUOTES,'UTF-8'));?></p><?php endif;?>
<?php if((int)$event->attachment_count>0):?><?php $calendar=new \Jugendtraining\Component\Jugendtraining\Site\Service\CalendarService();$attachments=$calendar->attachments((int)$event->id);?><div class="d-flex flex-wrap gap-2"><?php foreach($attachments as$a):?><a class="btn btn-sm btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_jugendtraining&task=calendarattachment.download&id='.(int)$a->id);?>">📎 <?php echo htmlspecialchars($a->file_name,ENT_QUOTES,'UTF-8');?></a><?php endforeach;?></div><?php endif;?>
</div></article></div><?php endforeach;?></div><?php else:?><div class="alert alert-info"><?php echo Text::_('COM_JUGENDTRAINING_NO_CALENDAR_EVENTS');?></div><?php endif;?>
