<?php
namespace Jugendtraining\Component\Jugendtraining\Site\Model;
\defined('_JEXEC') or die;
use Joomla\CMS\Factory;use Joomla\CMS\MVC\Model\BaseDatabaseModel;use Jugendtraining\Component\Jugendtraining\Site\Service\AccessService;use Jugendtraining\Component\Jugendtraining\Site\Service\BadgeUploadService;
final class TrainerachievementeditModel extends BaseDatabaseModel{
 private function guard():void{if(!(new AccessService())->isTrainer())throw new \RuntimeException('JERROR_ALERTNOAUTHOR',403);}
 public function getAvailableBadges():array{return(new BadgeUploadService())->listAvailable();}
 public function getItem():object{$this->guard();$id=Factory::getApplication()->input->getInt('id');if(!$id)return(object)['id'=>0,'title'=>'','code'=>'','description'=>'','category'=>'','award_mode'=>'manual','rule_type'=>'','rule_value'=>'','rule_terms'=>'','requires_verified_result'=>0,'badge_image'=>'','ordering'=>0,'published'=>1];$db=$this->getDatabase();$q=$db->getQuery(true)->select('*')->from($db->quoteName('#__jt_achievements'))->where('id='.$id);$db->setQuery($q);return$db->loadObject()?:throw new \RuntimeException('JERROR_LAYOUT_REQUESTED_RESOURCE_WAS_NOT_FOUND',404);}
 public function save(array$data,?array$upload):int{$this->guard();$db=$this->getDatabase();$id=(int)($data['id']??0);$title=trim((string)($data['title']??''));$code=trim((string)($data['code']??''));if($title===''||!preg_match('/^[a-z0-9_-]+$/',$code))throw new \RuntimeException('COM_JUGENDTRAINING_ERROR_ACHIEVEMENT_CODE');$path=(new BadgeUploadService())->store($upload);$mode=($data['award_mode']??'manual')==='automatic'?'automatic':'manual';$rule=$mode==='automatic'?trim((string)($data['rule_type']??'')):null;if($mode==='automatic'&&!in_array($rule,['arrows_single_day','arrows_calendar_week','diary_week_streak','event_name_contains'],true))throw new \RuntimeException('COM_JUGENDTRAINING_ERROR_RULE_REQUIRED');$verified=$rule==='event_name_contains'?1:(int)($data['requires_verified_result']??0);$fields=['title'=>$title,'code'=>$code,'description'=>trim((string)($data['description']??''))?:null,'category'=>trim((string)($data['category']??'general'))?:'general','award_mode'=>$mode,'rule_type'=>$rule,'rule_value'=>$mode==='automatic'&&($data['rule_value']??'')!==''?(float)str_replace(',','.',(string)$data['rule_value']):null,'rule_terms'=>$rule==='event_name_contains'?trim((string)($data['rule_terms']??'')):null,'requires_verified_result'=>$verified,'ordering'=>(int)($data['ordering']??0),'published'=>(int)($data['published']??1)];if($path){$fields['badge_image']=$path;}elseif(!empty($data['badge_image_existing'])){$fields['badge_image']=trim((string)$data['badge_image_existing']);}$now=Factory::getDate()->toSql();$uid=(int)Factory::getApplication()->getIdentity()->id;if($id){$fields['modified']=$now;$fields['modified_by']=$uid;$q=$db->getQuery(true)->update($db->quoteName('#__jt_achievements'))->where('id='.$id);}else{$fields['created']=$now;$fields['created_by']=$uid;$q=$db->getQuery(true)->insert($db->quoteName('#__jt_achievements'));}$sets=[];foreach($fields as$k=>$v)$sets[]=$db->quoteName($k).'='.($v===null?'NULL':$db->quote($v));if($id)$q->set($sets);else{$q->columns(array_map([$db,'quoteName'],array_keys($fields)))->values(implode(',',array_map(fn($v)=>$v===null?'NULL':$db->quote($v),array_values($fields))));}$db->setQuery($q)->execute();return$id?:$db->insertid();}
 public function delete(int$id):void{$this->guard();$db=$this->getDatabase();$q=$db->getQuery(true)->delete($db->quoteName('#__jt_achievements'))->where('id='.$id);$db->setQuery($q)->execute();}
}
