<?php
\defined('_JEXEC') or die;use Joomla\CMS\Language\Text;use Joomla\CMS\Router\Route;use Joomla\CMS\HTML\HTMLHelper;use Joomla\CMS\Uri\Uri;$a=$this->item;?>
<h1><?php echo$a->id?Text::_('COM_JUGENDTRAINING_ACHIEVEMENT_EDIT'):Text::_('COM_JUGENDTRAINING_ACHIEVEMENT_NEW');?></h1>
<form action="<?php echo Route::_('index.php?option=com_jugendtraining&task=achievementdefinition.save');?>" method="post" enctype="multipart/form-data">
<div class="row g-4"><div class="col-lg-8"><div class="card"><div class="card-body">
<div class="mb-3"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_TITLE');?></label><input class="form-control" name="title" value="<?php echo htmlspecialchars($a->title,ENT_QUOTES,'UTF-8');?>" required></div>
<div class="mb-3"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_ACHIEVEMENT_CODE');?></label><input class="form-control" name="code" pattern="[a-z0-9_-]+" value="<?php echo htmlspecialchars($a->code,ENT_QUOTES,'UTF-8');?>" required><div class="form-text"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_ACHIEVEMENT_CODE_DESC');?></div></div>
<div class="mb-3"><label class="form-label"><?php echo Text::_('JGLOBAL_DESCRIPTION');?></label><textarea class="form-control" name="description"><?php echo htmlspecialchars((string)$a->description,ENT_QUOTES,'UTF-8');?></textarea></div>
<div class="mb-3"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_CATEGORY');?></label><input class="form-control" name="category" value="<?php echo htmlspecialchars($a->category,ENT_QUOTES,'UTF-8');?>" required></div>
<div class="mb-3"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_AWARD_MODE');?></label><select class="form-select" name="award_mode" id="award_mode"><option value="manual" <?php echo$a->award_mode==='manual'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_AWARD_MANUAL');?></option><option value="automatic" <?php echo$a->award_mode==='automatic'?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_AWARD_AUTOMATIC');?></option></select></div>
<div id="automatic_fields"><div class="mb-3"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_RULE_TYPE');?></label><select class="form-select" name="rule_type" id="rule_type"><option value=""><?php echo Text::_('COM_JUGENDTRAINING_SELECT_RULE');?></option><?php foreach(['arrows_single_day','arrows_calendar_week','diary_week_streak','event_name_contains'] as$r):?><option value="<?php echo$r;?>" <?php echo$a->rule_type===$r?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_RULE_'.strtoupper($r));?></option><?php endforeach;?></select></div>
<div class="mb-3"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_RULE_VALUE');?></label><input class="form-control" type="number" min="1" step="1" name="rule_value" value="<?php echo htmlspecialchars((string)$a->rule_value,ENT_QUOTES,'UTF-8');?>"></div>
<div class="mb-3" id="terms_field"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_RULE_TERMS');?></label><input class="form-control" name="rule_terms" value="<?php echo htmlspecialchars((string)$a->rule_terms,ENT_QUOTES,'UTF-8');?>"><div class="form-text"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_RULE_TERMS_DESC');?></div><div class="alert alert-info mt-2 mb-0"><?php echo Text::_('COM_JUGENDTRAINING_VERIFIED_EVENT_RULE_NOTICE');?></div></div></div>
<div class="row g-3"><div class="col-md-6"><label class="form-label"><?php echo Text::_('JFIELD_ORDERING_LABEL');?></label><input class="form-control" type="number" name="ordering" value="<?php echo(int)$a->ordering;?>"></div><div class="col-md-6"><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_STATUS');?></label><select class="form-select" name="published"><option value="1" <?php echo$a->published?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_STATUS_PUBLISHED');?></option><option value="0" <?php echo!$a->published?'selected':'';?>><?php echo Text::_('COM_JUGENDTRAINING_STATUS_UNPUBLISHED');?></option></select></div></div>
</div></div></div><div class="col-lg-4"><div class="card"><div class="card-header"><h2 class="h5 mb-0"><?php echo Text::_('COM_JUGENDTRAINING_BADGE_GRAPHIC');?></h2></div><div class="card-body"><?php if($a->badge_image):?><img class="img-fluid mb-3" src="<?php echo htmlspecialchars(Uri::root().ltrim($a->badge_image,'/'),ENT_QUOTES,'UTF-8');?>" alt=""><?php endif;?><div class="mb-3"><label class="form-label" for="badge_image_existing"><?php echo Text::_('COM_JUGENDTRAINING_SELECT_EXISTING_BADGE');?></label><select class="form-select" id="badge_image_existing" name="badge_image_existing"><option value=""><?php echo Text::_('COM_JUGENDTRAINING_NO_BADGE_SELECTED');?></option><?php foreach($this->availableBadges as$badge):?><option value="<?php echo htmlspecialchars($badge['value'],ENT_QUOTES,'UTF-8');?>" <?php echo (string)$a->badge_image===(string)$badge['value']?'selected':'';?>><?php echo htmlspecialchars($badge['text'],ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div><label class="form-label"><?php echo Text::_('COM_JUGENDTRAINING_UPLOAD_PNG');?></label><input class="form-control" type="file" name="badge_upload" accept="image/png"><div class="form-text"><?php echo Text::_('COM_JUGENDTRAINING_UPLOAD_PNG_DESC');?></div></div></div></div></div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary"><?php echo Text::_('COM_JUGENDTRAINING_BUTTON_SAVE');?></button><a class="btn btn-secondary" href="<?php echo Route::_('index.php?option=com_jugendtraining&view=trainerachievementdefinitions');?>"><?php echo Text::_('COM_JUGENDTRAINING_BUTTON_CANCEL');?></a></div><input type="hidden" name="id" value="<?php echo(int)$a->id;?>"><?php echo HTMLHelper::_('form.token');?></form>
<?php if($a->id):?><form class="mt-3" action="<?php echo Route::_('index.php?option=com_jugendtraining&task=achievementdefinition.delete');?>" method="post" onsubmit="return confirm('<?php echo htmlspecialchars(Text::_('COM_JUGENDTRAINING_CONFIRM_DELETE'),ENT_QUOTES,'UTF-8');?>');"><input type="hidden" name="id" value="<?php echo(int)$a->id;?>"><button class="btn btn-outline-danger"><?php echo Text::_('COM_JUGENDTRAINING_BUTTON_DELETE');?></button><?php echo HTMLHelper::_('form.token');?></form><?php endif;?>
<script>document.addEventListener('DOMContentLoaded',()=>{const mode=document.getElementById('award_mode'),rule=document.getElementById('rule_type'),auto=document.getElementById('automatic_fields'),terms=document.getElementById('terms_field');const refresh=()=>{auto.hidden=mode.value!=='automatic';terms.hidden=rule.value!=='event_name_contains'};mode.addEventListener('change',refresh);rule.addEventListener('change',refresh);refresh()});</script>
