<?php
namespace Jugendtraining\Component\Jugendtraining\Administrator\Model;
\defined('_JEXEC') or die;
use Joomla\CMS\Factory;use Joomla\CMS\MVC\Model\BaseDatabaseModel;
final class CalendarModel extends BaseDatabaseModel{
 public function getCategories():array{$db=$this->getDatabase();$q=$db->getQuery(true)->select('setting_value')->from('#__jt_settings')->where('setting_key='.$db->quote('calendar_categories'));$db->setQuery($q);$v=json_decode((string)$db->loadResult(),true);return is_array($v)&&$v?$v:['Liga','Wettkampf','Training','Lehrgang','Vereinstermin','Sonstiges'];}
 public function getLocations():array{$db=$this->getDatabase();$q=$db->getQuery(true)->select('DISTINCT location')->from('#__jt_calendar_events')->where("location IS NOT NULL")->where("location<>''")->order('location');$db->setQuery($q);return$db->loadColumn();}
 public function getEvents():array{$i=Factory::getApplication()->input;$db=$this->getDatabase();$mode=$i->getCmd('mode','future');$q=$db->getQuery(true)->select(['e.*','COUNT(a.id) attachment_count'])->from('#__jt_calendar_events e')->leftJoin('#__jt_calendar_attachments a ON a.event_id=e.id');$today=Factory::getDate()->format('Y-m-d');if($mode==='future')$q->where('e.event_date>='.$db->quote($today));elseif($mode==='past')$q->where('e.event_date<'.$db->quote($today));$from=$i->getString('date_from');$to=$i->getString('date_to');if($this->validDate($from))$q->where('e.event_date>='.$db->quote($from));if($this->validDate($to))$q->where('e.event_date<='.$db->quote($to));$cat=$i->getString('category');$loc=$i->getString('location');if($cat!==''&&in_array($cat,$this->getCategories(),true))$q->where('e.category='.$db->quote($cat));if($loc!=='')$q->where('e.location='.$db->quote($loc));$q->group('e.id')->order($mode==='past'?'e.event_date DESC,e.event_time DESC':'e.event_date ASC,e.event_time ASC');$db->setQuery($q);return$db->loadObjectList();}
 public function getEditEvent():?object{$id=Factory::getApplication()->input->getInt('edit_id');if(!$id)return null;$db=$this->getDatabase();$q=$db->getQuery(true)->select('*')->from('#__jt_calendar_events')->where('id='.$id);$db->setQuery($q);$e=$db->loadObject();if($e)$e->attachments=$this->attachments($id);return$e?:null;}
 public function save(array$d,mixed$uploads):int{$db=$this->getDatabase();$id=(int)($d['id']??0);$title=trim((string)($d['title']??''));$date=trim((string)($d['event_date']??''));$time=trim((string)($d['event_time']??''));$loc=trim((string)($d['location']??''));$cat=trim((string)($d['category']??''));$desc=trim((string)($d['description']??''));if($title===''||mb_strlen($title)>190)throw new \RuntimeException('Ungültiger Titel.');if(!$this->validDate($date))throw new \RuntimeException('Ungültiges Datum.');if($time!==''&&!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/',$time))throw new \RuntimeException('Ungültige Uhrzeit.');if(!in_array($cat,$this->getCategories(),true))throw new \RuntimeException('Ungültige Kategorie.');if(mb_strlen($loc)>190||mb_strlen($desc)>10000)throw new \RuntimeException('Eingabe ist zu lang.');$now=Factory::getDate()->toSql();$uid=(int)Factory::getApplication()->getIdentity()->id;$o=(object)['title'=>$title,'event_date'=>$date,'event_time'=>$time?:null,'location'=>$loc?:null,'category'=>$cat,'description'=>$desc?:null,'published'=>!empty($d['published'])?1:0,'modified'=>$now,'modified_by'=>$uid];if($id){$o->id=$id;$db->updateObject('#__jt_calendar_events',$o,'id');}else{$o->created=$now;$o->created_by=$uid;$db->insertObject('#__jt_calendar_events',$o);$id=(int)$db->insertid();}$this->storeUploads($id,$uploads);return$id;}
 public function delete(int$id):void{if($id<=0)return;$db=$this->getDatabase();$q=$db->getQuery(true)->delete('#__jt_calendar_events')->where('id='.$id);$db->setQuery($q)->execute();}
 public function attachments(int$id):array{$db=$this->getDatabase();$q=$db->getQuery(true)->select(['id','file_name','file_size'])->from('#__jt_calendar_attachments')->where('event_id='.$id)->order('id');$db->setQuery($q);return$db->loadObjectList();}
 private function validDate(string$v):bool{if($v==='')return false;$x=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);return$x&&$x->format('Y-m-d')===$v;}
 private function storeUploads(int$id,mixed$uploads):void{$files=$this->normalise($uploads);if(count($files)>5)throw new \RuntimeException('Maximal fünf PDFs pro Upload.');$db=$this->getDatabase();foreach($files as$f){$err=(int)($f['error']??UPLOAD_ERR_NO_FILE);if($err===UPLOAD_ERR_NO_FILE)continue;if($err!==UPLOAD_ERR_OK)throw new \RuntimeException('PDF-Upload fehlgeschlagen.');$tmp=(string)($f['tmp_name']??'');$size=(int)($f['size']??0);if($size<=0||$size>8*1024*1024||!is_file($tmp))throw new \RuntimeException('PDF ist leer oder größer als 8 MB.');if((string)@file_get_contents($tmp,false,null,0,5)!=='%PDF-')throw new \RuntimeException('Nur PDF erlaubt.');$fi=new \finfo(FILEINFO_MIME_TYPE);if((string)$fi->file($tmp)!=='application/pdf')throw new \RuntimeException('Nur PDF erlaubt.');$raw=file_get_contents($tmp);$name=basename((string)($f['name']??'Anhang.pdf'));$name=preg_replace('/[^\pL\pN._ -]+/u','_',$name)?:'Anhang.pdf';if(!str_ends_with(strtolower($name),'.pdf'))$name.='.pdf';$o=(object)['event_id'=>$id,'file_name'=>mb_substr($name,0,190),'mime_type'=>'application/pdf','file_size'=>$size,'file_data'=>base64_encode($raw),'created'=>Factory::getDate()->toSql(),'created_by'=>(int)Factory::getApplication()->getIdentity()->id];$db->insertObject('#__jt_calendar_attachments',$o);}}
 private function normalise(mixed$u):array{if(!is_array($u))return[];if(isset($u['name'])&&is_array($u['name'])){$r=[];foreach($u['name']as$i=>$n)$r[]=['name'=>$n,'tmp_name'=>$u['tmp_name'][$i]??'','error'=>$u['error'][$i]??UPLOAD_ERR_NO_FILE,'size'=>$u['size'][$i]??0];return$r;}if(isset($u['name']))return[$u];return array_values(array_filter($u,'is_array'));}
}
