CREATE TABLE IF NOT EXISTS `#__jt_results` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `athlete_id` int unsigned NOT NULL,
  `result_date` date NOT NULL,
  `event_type` varchar(30) NOT NULL DEFAULT 'training',
  `event_name` varchar(190) DEFAULT NULL,
  `distance_m` int unsigned NOT NULL DEFAULT 18,
  `arrows` int unsigned NOT NULL DEFAULT 0,
  `score` int unsigned NOT NULL DEFAULT 0,
  `average` decimal(8,3) NOT NULL DEFAULT 0.000,
  `tens` int unsigned NOT NULL DEFAULT 0,
  `xs` int unsigned NOT NULL DEFAULT 0,
  `notes` text DEFAULT NULL,
  `published` tinyint NOT NULL DEFAULT 1,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int unsigned NOT NULL DEFAULT 0,
  `modified` datetime DEFAULT NULL,
  `modified_by` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_jt_results_athlete` (`athlete_id`),
  KEY `idx_jt_results_date` (`result_date`),
  KEY `idx_jt_results_event_type` (`event_type`),
  KEY `idx_jt_results_distance` (`distance_m`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
