<?php
\defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper; use Joomla\CMS\Language\Text; use Joomla\CMS\Router\Route;
HTMLHelper::_('behavior.multiselect');
?>
<form action="<?php echo Route::_('index.php?option=com_jugendtraining&view=athletes'); ?>" method="post" name="adminForm" id="adminForm">
<div class="row g-2 mb-3 align-items-end"><div class="col-lg-5"><label class="form-label" for="filter_search"><?php echo Text::_('JSEARCH_FILTER'); ?></label><input id="filter_search" class="form-control" type="search" name="filter_search" value="<?php echo htmlspecialchars((string)$this->state->get('filter.search'),ENT_QUOTES,'UTF-8'); ?>" placeholder="<?php echo Text::_('COM_JUGENDTRAINING_SEARCH_ATHLETES_EXTENDED'); ?>"></div><div class="col-md-3"><label class="form-label" for="filter_club_id"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_CLUB'); ?></label><select class="form-select" id="filter_club_id" name="filter_club_id"><option value="0"><?php echo Text::_('COM_JUGENDTRAINING_FILTER_ALL_CLUBS'); ?></option><?php foreach($this->clubs as$club):?><option value="<?php echo(int)$club->id;?>" <?php echo(int)$this->state->get('filter.club_id')===(int)$club->id?'selected':'';?>><?php echo htmlspecialchars((string)$club->name,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label" for="filter_bow_type"><?php echo Text::_('COM_JUGENDTRAINING_FIELD_BOW_TYPE'); ?></label><select class="form-select" id="filter_bow_type" name="filter_bow_type"><option value=""><?php echo Text::_('COM_JUGENDTRAINING_FILTER_ALL_BOW_TYPES'); ?></option><?php foreach($this->bowTypes as$bowType):?><option value="<?php echo htmlspecialchars($bowType,ENT_QUOTES,'UTF-8');?>" <?php echo(string)$this->state->get('filter.bow_type')===$bowType?'selected':'';?>><?php echo htmlspecialchars($bowType,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100" type="submit"><?php echo Text::_('JSEARCH_FILTER_SUBMIT'); ?></button></div></div>
<table class="table table-striped"><thead><tr><th width="1%"><input type="checkbox" name="checkall-toggle" value="" onclick="Joomla.checkAll(this)"></th><th><?php echo HTMLHelper::_('grid.sort','COM_JUGENDTRAINING_NAME','a.lastname',$this->state->get('list.direction'),$this->state->get('list.ordering')); ?></th><th><?php echo HTMLHelper::_('grid.sort','COM_JUGENDTRAINING_FIELD_CLUB','c.name',$this->state->get('list.direction'),$this->state->get('list.ordering')); ?></th><th><?php echo Text::_('COM_JUGENDTRAINING_FIELD_CLASS'); ?></th><th><?php echo HTMLHelper::_('grid.sort','COM_JUGENDTRAINING_FIELD_BOW_TYPE','a.bow_type',$this->state->get('list.direction'),$this->state->get('list.ordering')); ?></th><th><?php echo Text::_('COM_JUGENDTRAINING_TRAINING_GROUPS'); ?></th><th><?php echo Text::_('COM_JUGENDTRAINING_COLUMN_STATUS'); ?></th><th>ID</th></tr></thead><tbody>
<?php foreach($this->items as $i=>$item): ?><tr><td><?php echo HTMLHelper::_('grid.id',$i,$item->id); ?></td><td><a href="<?php echo Route::_('index.php?option=com_jugendtraining&task=athlete.edit&id='.(int)$item->id); ?>"><?php echo htmlspecialchars((string)($item->lastname . ', ' . $item->firstname),ENT_QUOTES,'UTF-8'); ?></a></td><td><?php echo htmlspecialchars((string)($item->club_name ?: '–'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string)($item->class_name ?: '–'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string)($item->bow_type ?: '–'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string)($item->group_names ?: '–'),ENT_QUOTES,'UTF-8'); ?></td><td><?php echo htmlspecialchars((string)($item->published ? Text::_('COM_JUGENDTRAINING_STATUS_PUBLISHED') : Text::_('COM_JUGENDTRAINING_STATUS_UNPUBLISHED')), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo (int)$item->id; ?></td></tr><?php endforeach; ?>
</tbody></table><?php echo $this->pagination->getListFooter(); ?>
<input type="hidden" name="task" value=""><input type="hidden" name="boxchecked" value="0"><input type="hidden" name="filter_order" value="<?php echo htmlspecialchars((string)$this->state->get('list.ordering'),ENT_QUOTES,'UTF-8'); ?>"><input type="hidden" name="filter_order_Dir" value="<?php echo htmlspecialchars((string)$this->state->get('list.direction'),ENT_QUOTES,'UTF-8'); ?>"><?php echo HTMLHelper::_('form.token'); ?></form>
